# Generated by Django 4.1.7 on 2023-03-13 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='dt',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
