# Generated by Django 4.1.7 on 2023-03-13 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reservations', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='review_rating',
            new_name='user_review_rating',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='host_reply1',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='host_reply1_dt',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='review_comment',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='review_dt',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='user_reply2_comment',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='user_reply2_dt',
        ),
        migrations.AddField(
            model_name='reservation',
            name='host_reply_comment',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='host_reply_dt',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='host_review_comment',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='host_review_dt',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='host_review_rating',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='user_reply_comment',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='user_reply_dt',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='user_review_comment',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='user_review_dt',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('DENIED', 'DENIED'), ('EXPIRED', 'EXPIRED'), ('APPROVED', 'APPROVED'), ('CANCELLED', 'CANCELLED'), ('TERMINATEDCOMPLETED', 'TERMINATEDCOMPLETED')], max_length=200),
        ),
    ]
