# Generated by Django 4.1.7 on 2023-04-05 02:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Properties', '0001_initial'),
        ('Listings', '0002_alter_listing_end_dt_alter_listing_start_dt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='Properties.property'),
        ),
    ]
